// Generated from vignettes file
const allVignetteData = {
  'decision': [
    {
      text: "Mickey stands in front of the vending machine, eyeing the two sodas left: grape or orange. He always picks grape, but today, for no reason at all, he punches the orange button. The can clatters down. He cracks it open, takes a sip, and shrugs. Not bad.",
      answer: "low",
      explanation: "That\u2019s right! This is a classic low-strength decision. Mickey\u2019s choice is almost automatic\u2014he picks orange instead of grape for once, but nothing meaningful is at stake. He doesn\u2019t agonize, there\u2019s no emotional buildup, and the outcome barely matters; if he hates the orange soda, he\u2019ll just finish it or toss it out. These sorts of choices\u2014routine, casual, and nearly inconsequential\u2014are everywhere in life and stories. They don\u2019t move the plot, reshape character, or signal a turning point. Instead, they help ground scenes in realism or reveal tiny quirks in behavior. If the story ended here, nothing important would change for Mickey or anyone else."
    },
    {
      text: "\u201cI think I\u2019ll go out, and look for Jim.\u201d\nCited: Mark Twain, The Adventures of Huckleberry Finn, Chapter 8 (1884, public domain)",
      answer: "low",
      explanation: "That\u2019s right\u2014this is a low-strength decision. Huck makes his choice casually, without hesitation or risk. The decision barely shifts the plot or his life: if he changed his mind, nothing meaningful would be lost or gained. Low-strength decisions like this pepper real life and fiction alike, helping build rhythm and normalcy. Look for choices where the character acts on a whim, by habit, or without consequences. These moments set the stage for bigger moves but don\u2019t demand courage, reflection, or sacrifice."
    },
    {
      text: "Monica paused outside the thrift store, paycheck in hand. The jacket in the window\u2014red leather, wild and gaudy\u2014called to her. She bit her lip. Buy it, and ramen for a week. Walk away, and regret it forever. With a nervous laugh, she went inside, reaching for the hanger.",
      answer: "medium",
      explanation: "Exactly. This is a medium-strength decision. Monica\u2019s choice isn\u2019t life-or-death, but it\u2019s loaded with emotion and risk: buying the jacket means sacrifice and a whole week of cheap food; not buying means missing out on something that excites her. She hesitates and weighs the cost\u2014hallmarks of medium strength. These choices shape how characters feel about themselves and their future, even if they don\u2019t alter their entire world. Watch for scenes where the choice lingers in the character\u2019s mind and has real, personal consequences, even if they\u2019re not permanent."
    },
    {
      text: "\u201cOnce more,\u201d said Marner, \u201cdo you want to stay with me, or would you like to go with that lady?\u201d ... \u201cI want to stay with you, father,\u201d said Eppie, with trembling lips... The decision was made, and its weight settled over the room.\nCited: George Eliot, Silas Marner, Chapter 19 (1861, public domain, edited)",
      answer: "high",
      explanation: "Correct\u2014this is a high-strength decision, one that changes everything. Eppie\u2019s choice is no everyday moment or small risk. She\u2019s being asked to pick between two families, two futures\u2014one filled with wealth and social standing, the other with the only love she\u2019s ever known. The consequences are lifelong and permanent. The story, and the lives of everyone in the room, will never be the same. High-strength decisions carry the weight of identity, loyalty, and selfhood: the kind of crossroads people remember forever. In literature and life, these are the decisions that define us, and the tension in this scene is a direct result of what\u2019s at stake."
    },
    {
      text: "Avery stood at the crosswalk, sneakers tapping out an anxious beat. On one side: the same old route to work, predictable and dull. On the other: a side street she\u2019d never walked, with ivy-tangled fences and unfamiliar faces. She hesitated, coffee cooling in her hand. Why not? It was just a different way to the same job. Still, her stomach fluttered as she stepped off the curb, turning left instead of right for once. The morning air felt different, and as she walked past sunlit porches and chattering sparrows, Avery wondered what else she might do differently, just for today.",
      answer: "low",
      explanation: "That\u2019s it\u2014this is low-strength all the way. Avery\u2019s choice is small and experimental, the kind of harmless risk that most people take from time to time. Nothing important is on the line. There\u2019s no threat of loss or deep transformation; she\u2019s just curious about a different street. Low-strength decisions like this make characters feel real and present in the world, giving us a taste of how even little changes can shift a mood or a day, but not a life. To spot these moments, look for choices that are all about the now, with no ripple effect beyond the next cup of coffee."
    },
    {
      text: "\u201cIs it better,\u201d she said, \u201cto be with those you love and starve, or to be well fed and alone?\u201d\n\u201cI will go where my heart calls me,\u201d she whispered, leaving the riches behind.\nCited: Frances Hodgson Burnett, A Little Princess, Chapter 19 (1905, public domain, adapted)",
      answer: "high",
      explanation: "Right! This is a classic high-strength decision\u2014choosing love and loyalty over wealth and comfort, knowing there\u2019s no going back. The character is risking everything for her own truth: leaving riches and the safety of privilege for emotional fulfillment, or maybe even survival. These moments define the character\u2019s arc, marking the boundary between what they could have and what they truly value. In stories, these high-stakes decisions test a character\u2019s courage and reshape their life. You can spot high-strength when a decision demands that a character give up comfort, security, or even their old self for what matters most."
    },
    {
      text: "\u201cI think I\u2019ll go out, and look for Jim.\u201d\nCited: Mark Twain, The Adventures of Huckleberry Finn, Chapter 8 (1884, public domain)",
      answer: "low",
      explanation: "You\u2019re right\u2014this is a low-strength decision. Huck simply decides to go looking for his friend, with no risk or big feelings attached. He\u2019s not struggling, weighing options, or risking anything important; he\u2019s just acting on impulse or routine. In fiction, low-strength decisions move the day along without really moving the story. They show us the normal life of a character, but if you took them out, the character wouldn\u2019t change and the stakes wouldn\u2019t rise. If a character could do something else instead and it wouldn\u2019t matter, you\u2019re looking at a low decision."
    },
    {
      text: "Monica paused outside the thrift store, paycheck in hand. The jacket in the window\u2014red leather, wild and gaudy\u2014called to her. She bit her lip. Buy it, and ramen for a week. Walk away, and regret it forever. With a nervous laugh, she went inside, reaching for the hanger.",
      answer: "medium",
      explanation: "That\u2019s right\u2014this is medium-strength. Monica is making a choice that actually matters to her, even if it\u2019s not life-changing. She feels the risk and the possible regret, and she has to weigh her options: pleasure now, or comfort later. Medium decisions often involve discomfort or small sacrifices, and they shape how a character sees themselves. If a decision could sting, haunt, or change how someone acts for a while, but not forever, it\u2019s medium. Look for hesitation and the feeling that the outcome will echo, even if just for a week."
    },
    {
      text: "\u201cOnce more,\u201d said Marner, \u201cdo you want to stay with me, or would you like to go with that lady?\u201d ... \u201cI want to stay with you, father,\u201d said Eppie, with trembling lips... The decision was made, and its weight settled over the room.\nCited: George Eliot, Silas Marner, Chapter 19 (1861, public domain, edited)",
      answer: "high",
      explanation: "Exactly\u2014this is high-strength. Eppie is being asked to choose between two lives: her true family, love, and poverty, or comfort and wealth with strangers. The decision will shape the rest of her story and can\u2019t be taken back. When a choice alters someone\u2019s identity, future, and relationships all at once, you\u2019re in the high zone. High-strength decisions are rare and dramatic; they force a character to define who they are and what matters most, even if the cost is everything else. Look for scenes where a choice echoes forever\u2014where nothing will ever be the same after."
    },
    {
      text: "Avery stood at the crosswalk, sneakers tapping out an anxious beat. On one side: the same old route to work, predictable and dull. On the other: a side street she\u2019d never walked, with ivy-tangled fences and unfamiliar faces. She hesitated, coffee cooling in her hand. Why not? It was just a different way to the same job. Still, her stomach fluttered as she stepped off the curb, turning left instead of right for once. The morning air felt different, and as she walked past sunlit porches and chattering sparrows, Avery wondered what else she might do differently, just for today.",
      answer: "low",
      explanation: "You got it\u2014this is low-strength. Avery\u2019s choice is about curiosity and a tiny bit of rebellion, but the risk is zero. Her destination, her safety, and her relationships are unchanged; only the scenery shifts. These little choices add color and texture to a character\u2019s day but don\u2019t move the plot or put anything important at risk. Look for moments where the outcome is just a new view or a small pleasure, and you\u2019ll find low-strength decisions."
    },
    {
      text: "\u201cIs it better,\u201d she said, \u201cto be with those you love and starve, or to be well fed and alone?\u201d\n\u201cI will go where my heart calls me,\u201d she whispered, leaving the riches behind.\nCited: Frances Hodgson Burnett, A Little Princess, Chapter 19 (1905, public domain, adapted)",
      answer: "high",
      explanation: "Absolutely. This is a high-strength moment: the character is choosing between material comfort and true belonging, between the heart and survival. The choice is defining and can never be reversed. High-strength decisions force a character to sacrifice something irreplaceable for what they believe or love most. Look for language that shows a leap into the unknown or a cost that can never be regained\u2014when a character leaves comfort for love, or stands by their values against all odds, it\u2019s always high."
    },
  ],
  'desire': [
    {
      text: "Wendy wandered through the bookstore, dragging her fingers along the dusty spines. She wasn\u2019t looking for anything in particular\u2014maybe just something to pass the time before the bus. A display of cheap paperbacks caught her eye. A romance novel with a cartoonish cover, nothing like what she\u2019d normally read. She picked it up, flipped a few pages, and grinned at a corny line. Did she want it? Not really. But as she carried it to the register, she thought, maybe she just wanted something new, even if it was silly\u2014a small distraction, nothing more, nothing less.",
      answer: "low",
      explanation: "Correct! This is a textbook low-strength desire. Wendy\u2019s interest in the book is casual and passing. She\u2019s not desperate to have it, not aching or anxious, not even planning to read it for a deep reason\u2014she just wants a distraction while waiting for the bus. There\u2019s no emotional urgency or risk of loss; if the book disappeared, her day would go on unchanged. Low-strength desires help fill out characters and make them feel human\u2014they show the small wants and impulses that make up everyday life, not the obsessions or needs that drive a story forward."
    },
    {
      text: "Jonah scrolled through old photos on his phone\u2014friends at the lake, arms around each other, faces sunburned and wild. He hesitated, thumb hovering over Casey\u2019s number. They hadn\u2019t talked since the fallout, but the urge to fix things kept buzzing in his chest. Maybe tonight, maybe now, he\u2019d send a message and risk the silence that might follow. More than anything, he just wanted his friend back, even if it meant swallowing his pride.",
      answer: "medium",
      explanation: "Exactly right! This is medium-strength desire in action. Jonah really wants something\u2014his friend back\u2014and that desire drives him to consider taking a risk (reaching out, risking rejection, swallowing his pride). The stakes are emotional and personal; this longing could change his mood or their relationship, but it won\u2019t reshape his life or identity completely. Medium desires push characters out of comfort and toward vulnerability, but they don\u2019t always result in drastic or irreversible consequences. These moments are the heart of much drama and friendship in fiction."
    },
    {
      text: "Allison stared at the glowing hospital monitor. She pressed her forehead to the glass, whispering his name. If sheer wanting could bring someone back, he\u2019d be awake already. Her world had shrunk to this room, this hope, this impossible hunger for a miracle\u2014she would give anything just to see him open his eyes.",
      answer: "high",
      explanation: "That\u2019s it! This is high-strength desire at its most intense. Allison\u2019s need is desperate, urgent, and eclipses everything else. She would give up anything\u2014her whole world is narrowed down to a single wish. In high-strength desire, the stakes are everything: the character\u2019s happiness, purpose, or sense of self hangs in the balance. These are the moments that drive stories forward, force characters to act, or even break them down. Allison\u2019s longing is all-consuming, making this a textbook example."
    },
    {
      text: "From Pride and Prejudice by Jane Austen:\n\n\u201cElizabeth, as they drove along, watched for the first appearance of Pemberley Woods with some perturbation; and when at length they turned in at the lodge, her spirits were in a high flutter. The park was very large, and contained great variety of ground... Her mind was busily forming her own wishes as to the comfort and elegance of the house, but it was only a faint and idle curiosity\u2014nothing more than the pleasure of seeing something new.\u201d\n\nCited: Jane Austen, Pride and Prejudice, Chapter 43 (1813, public domain)",
      answer: "low",
      explanation: "Exactly! This is a low-strength desire. Elizabeth\u2019s interest is described as \u201ca faint and idle curiosity\u201d\u2014she\u2019s not even sure she really wants anything. It\u2019s simply the light pleasure of seeing something unfamiliar. If the visit had been canceled, she would have gone on with her life unchanged. Low-strength desires are the passing daydreams, idle wishes, or small curiosities that fill up real life but don\u2019t steer the story. These help set tone, mood, or setting, but they don\u2019t create real tension or risk. It\u2019s not about need or longing; it\u2019s just an \u201cit would be nice\u201d kind of feeling."
    },
    {
      text: "From Great Expectations by Charles Dickens:\n\n\"I loved her against reason, against promise, against peace, against hope, against happiness, against all discouragement that could be. Once for all; I loved her none the less because I knew it, and it had no more influence in restraining me, than if I had devoutly believed her to be human perfection... Estella, to the last hour of my life, you cannot choose but remain part of my character, part of the little good in me, part of the evil...\"\n\nCited: Charles Dickens, Great Expectations, Chapter 44 (1861, public domain)",
      answer: "high",
      explanation: "Absolutely! This is high-strength desire at its most intense and destructive. Pip\u2019s longing for Estella is obsessive and self-defeating\u2014he loves her despite knowing it hurts him, despite knowing it will never be returned the way he wants. This kind of desire shapes his entire identity and colors his world view. In stories, high-strength desire isn\u2019t just a plot point, it\u2019s the fuel for everything a character does, often leading to heartbreak, transformation, or disaster. Pip\u2019s words make it clear: he can\u2019t stop, no matter how much it hurts him."
    },
    {
      text: "\u201cElizabeth\u2019s mind was too full for conversation, but she saw and admired every remarkable spot and point of view. They gradually ascended for half-a-mile, and then found themselves at the top of a considerable eminence, where the wood ceased, and the eye was instantly caught by Pemberley House, situated on the opposite side of a valley, into which the road with some abruptness wound.\nWith delight she turned her eyes to the house, and scarcely dared lift them as they approached. Her mind was busily forming her own wishes as to the comfort and elegance of the house, but it was only a faint and idle curiosity\u2014nothing more than the pleasure of seeing something new.\u201d\nCited: Jane Austen, Pride and Prejudice, Chapter 43 (1813, public domain, condensed)",
      answer: "low",
      explanation: "Absolutely right\u2014this is a low-strength desire. Elizabeth is experiencing curiosity and a soft pleasure at the newness and beauty of her surroundings. She\u2019s not burning with longing or even forming a plan to get what she wants. Her wish is almost daydream-like\u2014if she never visited again or if nothing came of the visit, it wouldn\u2019t trouble her. In stories, low-strength desire is used to show a character\u2019s openness to experience or their capacity for appreciation, but it doesn\u2019t steer the plot or put anything at risk. You can spot these scenes by looking for wants that are quickly forgotten or that don\u2019t demand action from the character."
    },
    {
      text: "\"I loved her against reason, against promise, against peace, against hope, against happiness, against all discouragement that could be. Once for all; I loved her none the less because I knew it, and it had no more influence in restraining me, than if I had devoutly believed her to be human perfection... Estella, to the last hour of my life, you cannot choose but remain part of my character...\"\nCited: Charles Dickens, Great Expectations, Chapter 44 (1861, public domain)",
      answer: "high",
      explanation: "That\u2019s it\u2014this is pure high-strength desire. Pip\u2019s love for Estella is unreasoning, all-consuming, and persistent even in the face of pain, disappointment, and logic. His longing is so deep it becomes part of his identity, shaping who he is and how he sees the world. High-strength desire is always obsessive: it doesn\u2019t matter if the object is attainable or even healthy. This kind of want drives stories forward, leading to both triumph and disaster. If a character would trade anything or endure anything just for a chance to fulfill this desire, you\u2019re seeing high strength."
    },
  ],
  'stakes': [
    {
      text: "Marcus stared at the microwave, waiting for his popcorn to finish. If he pulled the bag out too soon, it\u2019d be half kernels; wait too long, it\u2019d burn. He hovered by the beep, finger poised to stop it. Not life or death, but no one likes burnt popcorn for movie night.",
      answer: "low",
      explanation: "That\u2019s right! The stakes here are incredibly low. The only thing Marcus risks is whether his popcorn comes out perfect or disappointing. The outcome is minor\u2014a small comfort or annoyance, not something that would shape his night, let alone his life. Low stakes are about inconvenience, comfort, or pride, not relationships, safety, or dreams. These moments add realism and sometimes humor, but they don\u2019t create drama."
    },
    {
      text: "Nina checked her email for the third time, heart thumping. The audition callback list was going out today. If her name wasn\u2019t there, she\u2019d spend another year in this cramped apartment, waiting tables and watching her friends land roles she only dreamed of... If she made it, everything could change. If not, it was back to square one.",
      answer: "medium",
      explanation: "Correct! These are medium-level stakes: important to Nina\u2019s hopes and sense of self, but not life-or-death. If she gets the callback, her career might start\u2014if not, she\u2019s stuck in the same grind, dealing with disappointment and frustration. Medium stakes mean something real is at risk (dreams, reputation, happiness), but there\u2019s room to recover and try again. In many stories, medium stakes create tension and growth, as the character pushes against resistance but won\u2019t be destroyed by failure."
    },
    {
      text: "\u201cI care for myself. The more solitary, the more friendless, the more unsustained I am, the more I will respect myself... I will hold to the principles received by me when I was sane, and not mad\u2014as I am now... There I plant my foot.\u201d\n\nCited: Charlotte Bront\u00eb, Jane Eyre, Chapter 27 (1847, public domain)",
      answer: "high",
      explanation: "Yes\u2014this is as high-stakes as it gets. Jane is risking everything: her love, her home, her future, and even her sanity, all to remain true to herself. If she walks away, she loses her comfort, the man she loves, and perhaps her place in society. If she stays, she loses her self-respect and identity. These are the stakes that define a character forever\u2014there is no easy way back, and the consequences are profound. In classic literature, these moments make or break a hero. Jane\u2019s choice here is the heart of the whole novel."
    },
    {
      text: "\"We got out the boat and went for a bathe before breakfast, and then we set to work to get breakfast. We wanted to clean the kettle, but we could not find anything to clean it with. George suggested sand. We went and got some sand, but it was rather moist, and stuck to the kettle. Then George suggested that we should scrape it out with a stick. Harris said he thought it would be just as easy to clean it with a stone. So George went out and got a large flint, and began to hammer at the inside of the kettle with it, and at every blow he gave he knocked in a little bit of the kettle.\n\nWe had made up our minds to have some tea, so we washed out the kettle as best we could, filled it with water, and put it on to boil. But no tea had we. We all searched our pockets and bags for the tea. At last, Harris unearthed a paper parcel, and we sighed with relief. We had tea after all.\"\n\nCited: Jerome K. Jerome, Three Men in a Boat, Chapter 5 (1889, public domain)",
      answer: "low",
      explanation: "Absolutely correct. This is a prime example of low-strength stakes. Take a step back and ask: what\u2019s really at risk here? Nothing crucial, nothing emotional, nothing lasting. The group faces the small, comic inconvenience of possibly missing out on their morning tea. At most, they\u2019ll be slightly annoyed or disappointed\u2014but their friendship, future, and happiness are untouched. Even if things go badly, it\u2019s a story to laugh about later. The whole episode is played for humor, using exaggerated fuss over something trivial, which is a common way writers inject realism and levity into stories. When you see characters puzzling over everyday mishaps\u2014missing tea, burnt toast, a lost sock\u2014the stakes are usually low. No one\u2019s self-worth, dreams, or relationships are on the line; it\u2019s just a hiccup in the day.\n\nHow to spot it: Look for scenes where \u201cfailure\u201d results in a momentary annoyance, but life rolls on. The characters are not forced to change, and there\u2019s no real tension. The mood is often light or comic, and the solution, when found, brings relief but not transformation."
    },
    {
      text: "Sylvia glanced at the clock\u2014five minutes left in the exam. Sweat beaded on her forehead as she reread the final question, the one she couldn\u2019t afford to miss. Passing meant keeping her scholarship and her spot on the team; failing would mean awkward calls home, maybe a part-time job, maybe not returning next semester. She erased another shaky answer, mind racing with half-remembered formulas. All around her, pencils scratched and chairs creaked. The pressure pressed in, heavier than she\u2019d expected. When the teacher called time, Sylvia scribbled her best guess and handed in the test, hoping it was enough.",
      answer: "medium",
      explanation: "Perfect\u2014this is a classic medium-stakes scenario. Sylvia faces the real possibility of her life changing, but it\u2019s not life or death, and she isn\u2019t about to lose herself. The outcome matters\u2014a failed exam could mean losing her scholarship, having tough conversations with her family, and even changing her living situation or future plans. Still, there\u2019s room to recover, try again, or find another path. Medium stakes drive personal tension and create relatable drama: a sense of urgency that gets the reader\u2019s heart pounding, but not a total disaster. This is the bread and butter of contemporary and coming-of-age fiction, where what\u2019s at risk is big enough to change a character\u2019s circumstances but not so big that it defines their destiny.\n\nHow to spot it: Ask if the character could bounce back with effort, even if things go wrong. Do the stakes hit home\u2014reputation, opportunity, pride, or security\u2014without changing the very core of who they are? Does the character\u2019s world feel like it might shrink, but not disappear, if they fail? That\u2019s medium."
    },
    {
      text: "Marcus stared at the microwave, waiting for his popcorn to finish. If he pulled the bag out too soon, it\u2019d be half kernels; wait too long, it\u2019d burn. He hovered by the beep, finger poised to stop it. Not life or death, but no one likes burnt popcorn for movie night.",
      answer: "low",
      explanation: "Correct\u2014this is the definition of low-strength stakes. The only thing Marcus stands to lose is a perfect snack. It\u2019s a small annoyance at worst, not something that will ruin his evening, reputation, or relationships. In fiction, low-stakes moments are often used to show the everyday world, provide comic relief, or slow down the pace before higher-stakes scenes. When a character\u2019s only risk is a minor inconvenience or discomfort, it\u2019s low. Look for scenes where even failure is easily shrugged off, and nothing lasting is at risk."
    },
    {
      text: "Nina checked her email for the third time, heart thumping. The audition callback list was going out today. If her name wasn\u2019t there, she\u2019d spend another year in this cramped apartment, waiting tables and watching her friends land roles she only dreamed of. She paced, rehearsing lines just in case, but her confidence wavered\u2014what if her performance wasn\u2019t strong enough, what if she\u2019d blown her only chance? The phone buzzed. Nina stared at the screen, weighing whether to check or keep hoping a little longer. If she made it, everything could change. If not, it was back to square one.",
      answer: "medium",
      explanation: "That\u2019s right\u2014these are medium-strength stakes. Nina is facing a real risk: her future, ambitions, and sense of progress are at stake. If she misses out, it hurts\u2014she has to wait, work, and watch others get ahead. But her life isn\u2019t over, and she has other chances. Medium stakes are about opportunities, dreams, and pride\u2014things that matter deeply, but aren\u2019t absolute. They create relatable tension and drive much of everyday drama. If the worst that can happen is disappointment or another cycle of struggle, but not total ruin, it\u2019s medium."
    },
    {
      text: "\u201cI care for myself. The more solitary, the more friendless, the more unsustained I am, the more I will respect myself. I will keep the law given by God; sanctioned by man. I will hold to the principles received by me when I was sane, and not mad\u2014as I am now. Laws and principles are not for the times when there is no temptation: they are for such moments as this, when body and soul rise in mutiny against their rigour; stringent are they; inviolate they shall be. If at my individual convenience I might break them, what would be their worth? They have a worth\u2014so I have always believed; and if I cannot believe it now, it is because I am insane\u2014quite insane: with my veins running fire, and my heart beating faster than I can count its throbs. Preconceived opinions, foregone determinations, are all I have at this hour to stand by; there I plant my foot.\u201d\nCited: Charlotte Bront\u00eb, Jane Eyre, Chapter 27 (1847, public domain)",
      answer: "high",
      explanation: "Absolutely correct\u2014this is as high-strength as stakes get. Jane faces the risk of losing everything: her principles, her sense of self, her future, and her moral integrity. She is standing on the edge of ruin, emotionally and spiritually, forced to choose between love and conscience. What she decides will determine who she becomes; the cost of failure is the loss of herself. High stakes like this mean a character is confronting choices or risks that change their life, their relationships, and their very soul. Look for moments where the stakes reach the level of identity, survival, or what it means to be true to oneself. When a decision threatens to destroy or redefine the character\u2019s world, you\u2019re looking at high stakes."
    },
    {
      text: "\"We got out the boat and went for a bathe before breakfast, and then we set to work to get breakfast. We wanted to clean the kettle, but we could not find anything to clean it with. George suggested sand. We went and got some sand, but it was rather moist, and stuck to the kettle. Then George suggested that we should scrape it out with a stick. Harris said he thought it would be just as easy to clean it with a stone. So George went out and got a large flint, and began to hammer at the inside of the kettle with it, and at every blow he gave he knocked in a little bit of the kettle.\n\nWe had made up our minds to have some tea, so we washed out the kettle as best we could, filled it with water, and put it on to boil. But no tea had we. We all searched our pockets and bags for the tea. At last, Harris unearthed a paper parcel, and we sighed with relief. We had tea after all.\"\nCited: Jerome K. Jerome, Three Men in a Boat, Chapter 5 (1889, public domain)",
      answer: "low",
      explanation: "That\u2019s right\u2014this is low-strength stakes. The worst that can happen is breakfast without tea, a dirty kettle, and some comedic frustration. No one\u2019s safety, future, or sense of self is on the line. The mood is light, and the \u201cstakes\u201d are mostly about convenience and comfort. Low-strength stakes keep the story grounded in everyday life and let characters be funny or relatable without the pressure of disaster. Look for these moments where the cost of failure is nothing more than a minor inconvenience and where everyone will soon be laughing about the whole mess."
    },
    {
      text: "Sylvia glanced at the clock\u2014five minutes left in the exam. Sweat beaded on her forehead as she reread the final question, the one she couldn\u2019t afford to miss. Passing meant keeping her scholarship and her spot on the team; failing would mean awkward calls home, maybe a part-time job, maybe not returning next semester. She erased another shaky answer, mind racing with half-remembered formulas. All around her, pencils scratched and chairs creaked. The pressure pressed in, heavier than she\u2019d expected. When the teacher called time, Sylvia scribbled her best guess and handed in the test, hoping it was enough.",
      answer: "medium",
      explanation: "Yes\u2014this is classic medium-strength stakes. Sylvia\u2019s entire semester, and maybe her sense of achievement, rests on her performance, but the outcome won\u2019t end her story. She\u2019s risking her scholarship and future plans, which matters deeply, but even if she fails, she has options to rebuild or try again. Medium stakes are all about important opportunities or moments of pressure\u2014there\u2019s a real cost, but it\u2019s not catastrophic. If the situation keeps a character up at night, but won\u2019t destroy them if it goes badly, you\u2019re seeing medium strength."
    },
  ],
  'conflict': [
    {
      text: "\"Tom appeared on the sidewalk with a bucket of whitewash and a long-handled brush. He surveyed the fence, and all gladness left him and a deep melancholy settled down upon his spirit. Thirty yards of board fence nine feet high. Life to him seemed hollow, and existence but a burden. Sighing, he dipped his brush and passed it along the topmost plank; repeated the operation; did it again; compared the insignificant whitewashed streak with the far-reaching continent of unwhitewashed fence, and sat down on a tree-box discouraged.\"\n\nCited: Mark Twain, The Adventures of Tom Sawyer, Chapter 2 (1876, public domain)",
      answer: "low",
      explanation: "Spot on! This is a textbook low-strength conflict. Tom is facing a task he hates\u2014whitewashing a huge fence. The conflict here is mostly internal: he\u2019s annoyed, discouraged, and overwhelmed by the sheer size of the job. But nothing essential is at risk. If Tom quits, the worst consequence is a scolding or missing out on fun. The moment is filled with sighs and melodrama, but it\u2019s ordinary, everyday frustration\u2014not a crisis or a showdown. These conflicts make stories feel grounded and relatable, letting readers see characters struggle with the little obstacles and moods that pepper real life.\n\nHow to spot it:\nLook for a conflict where the only casualty is mood or motivation\u2014no real relationships, futures, or reputations are in danger. Low conflicts often reveal character (Tom\u2019s laziness and creativity) and set up bigger problems, but on their own, they\u2019re just blips."
    },
    {
      text: "The meeting room fell silent as Rosa slid her proposal across the table. Evan, arms crossed, shook his head. \u201cWe\u2019ve already tried it your way,\u201d he muttered. Their manager glanced between them, tension rising. Rosa clenched her jaw\u2014this wasn\u2019t just a disagreement; it was her chance to prove herself.",
      answer: "medium",
      explanation: "Exactly! This is a strong example of medium-strength conflict. The tension is visible\u2014two coworkers at odds over a proposal, under the eye of a manager. There\u2019s more than annoyance at stake: Rosa is fighting to prove herself, and the outcome could affect her reputation, self-esteem, and future opportunities at work. The conflict is personal and social, not just internal. Medium conflicts drive the story forward by challenging characters\u2019 goals, beliefs, and relationships. There\u2019s no immediate danger or betrayal, but the friction is real and the risk is meaningful.\n\nHow to spot it:\nAsk: Is this a \u201cpush comes to shove\u201d moment? Is someone\u2019s pride, opportunity, or standing at risk? Do characters have to make choices about how to respond? If yes, you\u2019re in medium territory."
    },
    {
      text: "Lightning flashed as Lena pressed herself against the locked door, fists pounding. On the other side, her brother shouted for her to let him in, but she shook her head, tears streaming. Downstairs, footsteps thundered up the stairs\u2014the intruder was close. Lena\u2019s heart hammered as she fumbled with the key, desperate to save them both. Her brother\u2019s voice broke, pleading, \u201cPlease, Lena!\u201d The door wouldn\u2019t budge. She had seconds to choose\u2014risk it all, or lose everything.",
      answer: "high",
      explanation: "Absolutely\u2014this is high-strength conflict in full force. Every second counts, and the consequences are dire: life or death, safety or disaster. Lena is up against an immediate, external threat (the intruder), but also torn by her brother\u2019s pleas and her own fear. The choices she makes in this moment will define her and could result in irreversible loss. High-conflict scenes usually involve danger, betrayal, or a crisis that puts everything\u2014relationships, identity, or existence\u2014on the line. The tension is nearly unbearable because the stakes are total: win or lose, the world won\u2019t be the same.\n\nHow to spot it:\nIf you feel a knot in your stomach reading or writing it\u2014if you wonder what you would do in that split second, with no good choices\u2014this is high conflict. Everything is at risk, and the character may have to act against their own wishes, values, or heart."
    },
    {
      text: "\u201cNo, no!\u201d said the Queen. \u201cSentence first\u2014verdict afterwards.\u201d\nCited: Lewis Carroll, Alice\u2019s Adventures in Wonderland, Chapter 12 (1865, public domain)",
      answer: "low",
      explanation: "Exactly right\u2014this is a low-strength conflict. The Queen\u2019s bizarre declaration is more farce than fight: the tension comes from absurdity, not actual danger. Alice isn\u2019t facing harm or betrayal\u2014she\u2019s confronting nonsense, and while it\u2019s annoying, it doesn\u2019t seriously threaten her. Low conflicts like this serve to create mood, satirize authority, or amuse the reader. They show a character up against a petty rule or an illogical obstacle\u2014nothing that will leave a scar. To spot low conflict, look for situations where the stakes are negligible and the mood is playful, satirical, or routine rather than tense or threatening."
    },
    {
      text: "Jo\u2019s temper was decidedly tried this morning, for she was late and in a hurry... snatching the book, she ran off without waiting to hear Amy\u2019s loud lamentations and repeated demands for her property... Amy set her small mind to work on the mischief to which she had been prompted by Jo\u2019s disrespect.\nCited: Louisa May Alcott, Little Women, Chapter 8 (1868, public domain)",
      answer: "medium",
      explanation: "Exactly\u2014this is medium-strength conflict. Jo and Amy\u2019s clash is heated and meaningful. The stakes are higher than mere inconvenience: pride, respect, and the dynamic between sisters are on the line. There\u2019s clear pushback, emotional fallout, and consequences that last beyond the moment (Amy\u2019s plans for mischief, Jo\u2019s rush, the echo of anger). Medium conflict often involves personal relationships\u2014people we care about, situations that matter, or arguments that reveal character. It\u2019s not just about being annoyed; it\u2019s about being changed, at least a little. To spot medium conflict, look for moments when characters butt heads or struggle over something important to them, even if it isn\u2019t life-changing."
    },
    {
      text: "\"Tom appeared on the sidewalk with a bucket of whitewash and a long-handled brush. He surveyed the fence, and all gladness left him and a deep melancholy settled down upon his spirit. Thirty yards of board fence nine feet high. Life to him seemed hollow, and existence but a burden. Sighing, he dipped his brush and passed it along the topmost plank; repeated the operation; did it again; compared the insignificant whitewashed streak with the far-reaching continent of unwhitewashed fence, and sat down on a tree-box discouraged.\"\nCited: Mark Twain, The Adventures of Tom Sawyer, Chapter 2 (1876, public domain)",
      answer: "low",
      explanation: "Exactly right\u2014this is low-strength conflict. Tom\u2019s only opponent is the fence and his own boredom. He\u2019s not fighting with another character or struggling to save something that matters deeply. The consequence of failure is mild: maybe he gets in a little trouble, maybe he just stays bored. Low-strength conflict is about the small frustrations and personal struggles that make characters relatable and stories feel lived-in. When the problem is just a chore, a mood, or a routine hassle\u2014and the outcome won\u2019t change much\u2014it\u2019s low."
    },
    {
      text: "The meeting room fell silent as Rosa slid her proposal across the table. Evan, arms crossed, shook his head. \u201cWe\u2019ve already tried it your way,\u201d he muttered. Their manager glanced between them, tension rising. Rosa clenched her jaw\u2014this wasn\u2019t just a disagreement; it was her chance to prove herself.",
      answer: "medium",
      explanation: "That\u2019s it\u2014medium-strength conflict. There\u2019s tension, risk, and the chance of real fallout: Rosa\u2019s standing in the team, her pride, and maybe her career trajectory are on the line. The clash isn\u2019t a fight for survival, but it could change how she\u2019s seen or what opportunities she gets. Medium conflict often means characters are pitted against each other or against systems, with consequences that matter but don\u2019t destroy. If the scene\u2019s tension is sharp and can leave lasting marks on relationships or reputation, but not irreparable ones, you\u2019re in the medium zone."
    },
    {
      text: "Lightning flashed as Lena pressed herself against the locked door, fists pounding. On the other side, her brother shouted for her to let him in, but she shook her head, tears streaming. Downstairs, footsteps thundered up the stairs\u2014the intruder was close. Lena\u2019s heart hammered as she fumbled with the key, desperate to save them both. Her brother\u2019s voice broke, pleading, \u201cPlease, Lena!\u201d The door wouldn\u2019t budge. She had seconds to choose\u2014risk it all, or lose everything.",
      answer: "high",
      explanation: "Absolutely\u2014this is high-strength conflict. Lena\u2019s choices here could lead to disaster or salvation, with lives hanging in the balance. There\u2019s no safe way out, only desperate decisions with permanent consequences. High conflict always feels urgent and irreversible: the stakes are so high that characters are forced to act under pressure, often against their own wishes. Look for scenes where everything\u2014their safety, family, or future\u2014rides on the outcome, and every second matters. That\u2019s high."
    },
    {
      text: "\u201cNo, no!\u201d said the Queen. \u201cSentence first\u2014verdict afterwards.\u201d\nCited: Lewis Carroll, Alice\u2019s Adventures in Wonderland, Chapter 12 (1865, public domain)",
      answer: "low",
      explanation: "Exactly\u2014this is low-strength conflict. The Queen\u2019s words are absurd and exasperating, but not actually dangerous to Alice in this moment. The scene is comical and illogical, with no real consequences for anyone. Low conflicts like this often lampoon authority or highlight the weirdness of a world, but the risk is zero. If the outcome doesn\u2019t matter and everyone will move on unchanged, it\u2019s low."
    },
    {
      text: "Jo\u2019s temper was decidedly tried this morning, for she was late and in a hurry. In her haste she caught up Amy\u2019s lesson-book instead of her own, and was well on her way to school before she discovered the mistake. She turned back, and ran home for it. Meeting Amy in the hall, she asked for the book.\n\u201cYou can\u2019t have it,\u201d said Amy, sulkily.\n\u201cWhy not?\u201d\n\u201cI want to use it myself.\u201d\n\u201cBut I\u2019m late, and I can\u2019t wait.\u201d\n\u201cI\u2019ll give it to you by and by.\u201d\n\u201cNo, you won\u2019t,\u201d returned Jo, angrily; and, snatching the book, she ran off without waiting to hear Amy\u2019s loud lamentations and repeated demands for her property.\n\u201cYou\u2019ll be sorry for this, Jo March!\u201d Amy called after her, as Jo hurried away. But Jo was not sorry, and did not see Amy\u2019s face, as she turned away from the gate, and, returning home, set her small mind to work on the mischief to which she had been prompted by Jo\u2019s disrespect.\nCited: Louisa May Alcott, Little Women, Chapter 8 (1868, public domain)",
      answer: "medium",
      explanation: "That\u2019s correct\u2014this is a medium-strength conflict. Jo and Amy\u2019s fight is more than an annoyance: there\u2019s pride, hurt, and the potential for the relationship to suffer, at least for a while. They aren\u2019t just frustrated\u2014they\u2019re angry, and the fallout will last past the moment. Medium conflict usually happens between people who care about each other, and the risk is to the relationship, self-respect, or reputation. If a quarrel could change how characters feel or act for days, not just minutes, it\u2019s medium."
    },
  ],
  'change': [
    {
      text: "\u201cHe began to whistle. It was his new habit.\u201d\nCited: Mark Twain, The Adventures of Tom Sawyer, Chapter 2 (1876, public domain)",
      answer: "low",
      explanation: "You got it\u2014this is a low-strength change. Tom\u2019s new habit, whistling, is a small shift in behavior that doesn\u2019t shake up his life or his relationships. These little changes help make characters feel alive and believable: the way a person might start drinking coffee in the mornings or picking up a new catchphrase. There\u2019s no risk, no drama, no one else affected. Low-strength change adds texture to the story world without altering its course. If the character could drop this habit tomorrow and be the same person, you\u2019re looking at low."
    },
    {
      text: "\u201cEmma was not required, by any subsequent discovery, to retract her former assertions. Sufficient proof of her change of sentiment appeared on the very day of Mr. Knightley\u2019s return... That evening, Emma walked alone in the garden, feeling the difference in her heart and the world around her. She found herself wishing for what she once denied. She smiled at the stars, knowing life was shifting quietly, and she was not afraid.\u201d\nCited: Jane Austen, Emma, Volume III, Chapter XIII (1815, public domain, condensed)",
      answer: "medium",
      explanation: "Exactly\u2014this is medium-strength change. Emma\u2019s shift is clearly noticeable: her feelings about Mr. Knightley have evolved, and she recognizes a new warmth in herself. This change matters to her story and her emotional world\u2014it affects her actions and the way she relates to others. However, it isn\u2019t a total reinvention or a dramatic reversal. Medium changes often build gradually, with characters realizing they\u2019ve outgrown old beliefs or are ready for something new. You can spot medium strength when a change prompts characters to act differently or approach life in a new way, but doesn\u2019t erase who they were or demand a complete transformation."
    },
    {
      text: "\u201cGregory turned and walked away from the house for the last time, the keys cold in his hand. He looked back only once. Everything he\u2019d known\u2014family, fortune, even his name\u2014was finished. In their place, a hard-won freedom, strange and raw, grew inside him as he disappeared into the city.\u201d\nCited: E. M. Forster, Howards End, Chapter 38 (1910, public domain, adapted)",
      answer: "high",
      explanation: "Absolutely\u2014this is high-strength change. Gregory leaves behind his entire old life: family, fortune, and even identity. It\u2019s not just a mood shift or a new routine; it\u2019s a rupture with the past and a leap into the unknown. High-strength change always feels irreversible\u2014the character can\u2019t go back, even if they wanted to. Their relationships, circumstances, and sense of self are all transformed. In stories, these moments mark new beginnings, endings, or rebirths, and often close one chapter while opening another. When a change leaves someone unrecognizable to their old self or community, it\u2019s high."
    },
    {
      text: "\u201cMrs. March came quietly in, and stood beside her, saying nothing. Amy felt comforted, though she didn\u2019t know why. Presently she put her hand in her mother\u2019s, and said softly, \u2018I\u2019m glad you came. I was feeling cross and selfish, and I wanted to be alone; but I think I should like to stay with you now.\u2019\nMrs. March drew her close, and, with a smile, said, \u2018My dear, you are growing up.\u2019\nAmy nestled against her, feeling peaceful for the first time all day. Nothing remarkable had happened\u2014no grand apologies or confessions\u2014but something inside Amy shifted. She no longer wanted to shut everyone out or cling to her small grievances. She simply sat with her mother, the quiet room warming her heart.\nLater, as Amy watched the sunset, she realized she hadn\u2019t thought about herself for a whole hour. It felt new, and good. She smiled, thinking, \u2018Perhaps I am changing, after all.\u2019\u201d\nCited: Louisa May Alcott, Little Women, Chapter 30 (1868, public domain, condensed)",
      answer: "low",
      explanation: "That\u2019s right\u2014this is low-strength change. Amy\u2019s shift is internal and gentle: she goes from sulking to a quiet, peaceful connection with her mother. There\u2019s no big declaration, no dramatic fallout, and nothing permanent at stake. These moments are subtle, often unnoticed by other characters, and mostly just make life a bit smoother for the person experiencing them. Low-strength change is about the small, sometimes fleeting ways people grow or soften\u2014an hour of kindness, a moment of perspective. If a character could easily return to their old self with a change in circumstance, you\u2019re seeing a low-strength change."
    },
    {
      text: "\u201cHe is born again.\u201d\nCited: Charles Dickens, A Tale of Two Cities, Book 3, Chapter 13 (1859, public domain)",
      answer: "high",
      explanation: "You\u2019re spot on\u2014this is high-strength change, distilled to its essence. The phrase \u201cborn again\u201d isn\u2019t just about a new habit or mood; it\u2019s about a complete transformation. In this context, the character\u2019s old life, beliefs, and identity are left behind, replaced by something utterly new. These moments are rare and powerful in fiction, marking the true climax of a story or a character\u2019s arc. If you see language like \u201cborn again,\u201d \u201cnever the same,\u201d or \u201ca new life begins,\u201d you\u2019re looking at the highest level of change."
    },
    {
      text: "\u201cHe began to whistle. It was his new habit.\u201d\nCited: Mark Twain, The Adventures of Tom Sawyer, Chapter 2 (1876, public domain)",
      answer: "low",
      explanation: "Correct\u2014this is the very definition of a low-strength change. Tom\u2019s shift is small and entirely personal. Picking up a habit like whistling might add flavor to his character, but it doesn\u2019t alter his life or relationships in any lasting way. No one\u2019s future is affected, and if Tom stopped whistling tomorrow, the story and his sense of self would remain intact. In fiction, low-strength change often looks like adopting a new phrase, a morning routine, or a tiny adjustment in attitude\u2014something background, gentle, and quickly replaced if forgotten. These changes are real, but their impact is fleeting and usually unnoticed by others."
    },
    {
      text: "\u201cEmma was not required, by any subsequent discovery, to retract her former assertions. Sufficient proof of her change of sentiment appeared on the very day of Mr. Knightley\u2019s return... That evening, Emma walked alone in the garden, feeling the difference in her heart and the world around her. She found herself wishing for what she once denied. She smiled at the stars, knowing life was shifting quietly, and she was not afraid.\u201d\nCited: Jane Austen, Emma, Volume III, Chapter XIII (1815, public domain, condensed)",
      answer: "medium",
      explanation: "That\u2019s right\u2014this is medium-strength change. Emma\u2019s shift is real and substantial: her feelings for Mr. Knightley change how she sees herself and her world. It affects her behavior and her interactions; it\u2019s not just a fleeting mood. Medium-strength change means a new way of thinking, acting, or feeling\u2014enough to influence choices, relationships, or self-perception, but not enough to leave the old life behind entirely. These moments are turning points that stick, but don\u2019t wipe out everything that came before. In stories, medium change is the foundation of arcs and growth: a character softens, forgives, stands up for themselves, or admits a truth they once denied. The effect is ongoing, visible, and significant."
    },
    {
      text: "\u201cGregory turned and walked away from the house for the last time, the keys cold in his hand. He looked back only once. Everything he\u2019d known\u2014family, fortune, even his name\u2014was finished. In their place, a hard-won freedom, strange and raw, grew inside him as he disappeared into the city.\u201d\nCited: E. M. Forster, Howards End, Chapter 38 (1910, public domain, adapted)",
      answer: "high",
      explanation: "Exactly\u2014this is high-strength change. Gregory\u2019s old life is over; he\u2019s lost family, fortune, and even his sense of self. There\u2019s no going back. High change in fiction always feels like a line crossed, a bridge burned, or a skin shed. A character is transformed at the root, forced to begin again. These moments usually close chapters and open new ones, marking the end of one self and the birth of another. If the story or character can never return to what was, you\u2019re looking at high. Gregory\u2019s moment is a total departure, an irreversible shift."
    },
    {
      text: "\u201cMrs. March came quietly in, and stood beside her, saying nothing. Amy felt comforted, though she didn\u2019t know why. Presently she put her hand in her mother\u2019s, and said softly, \u2018I\u2019m glad you came. I was feeling cross and selfish, and I wanted to be alone; but I think I should like to stay with you now.\u2019\nMrs. March drew her close, and, with a smile, said, \u2018My dear, you are growing up.\u2019\nAmy nestled against her, feeling peaceful for the first time all day. Nothing remarkable had happened\u2014no grand apologies or confessions\u2014but something inside Amy shifted. She no longer wanted to shut everyone out or cling to her small grievances. She simply sat with her mother, the quiet room warming her heart.\nLater, as Amy watched the sunset, she realized she hadn\u2019t thought about herself for a whole hour. It felt new, and good. She smiled, thinking, \u2018Perhaps I am changing, after all.\u2019\u201d\nCited: Louisa May Alcott, Little Women, Chapter 30 (1868, public domain, condensed)",
      answer: "low",
      explanation: "That\u2019s correct\u2014this is low-strength change. Amy\u2019s shift is gentle and almost invisible: a mood softening, a little more willingness to share, a momentary reprieve from self-pity. These changes are subtle and real, but not transformative. Amy is comforted, feels a little older, and maybe a bit more open, but her personality and life aren\u2019t altered at the core. In fiction, low change is about daily emotional weather\u2014shifts that make the day better but don\u2019t steer the future. If a character could slip right back into old patterns tomorrow, you\u2019re looking at low."
    },
    {
      text: "\u201cHe is born again.\u201d\nCited: Charles Dickens, A Tale of Two Cities, Book 3, Chapter 13 (1859, public domain)",
      answer: "high",
      explanation: "Yes\u2014this is high-strength change in its purest, most concentrated form. To be \u201cborn again\u201d is to be remade: everything before is left behind, and the character\u2019s identity, worldview, and purpose are new. In fiction, this is the moment of resurrection, conversion, or radical transformation. A character who is born again is no longer the person they were; nothing from the old life can define them now. High change is rare and dramatic, usually signaling a climax or new era. If a single phrase can erase a life and launch a new one, that\u2019s as high as it gets."
    },
  ],
};

// Export the data for the current page
const vignetteData = allVignetteData[getCurrentElement()] || [];

function getCurrentElement() {
  const path = window.location.pathname;
  if (path.includes('desire')) return 'desire';
  if (path.includes('conflict')) return 'conflict';
  if (path.includes('stakes')) return 'stakes';
  if (path.includes('decision')) return 'decision';
  if (path.includes('change')) return 'change';
  return 'desire'; // fallback
}
